repo_name: "CreaProFDR"
repo_icon: "icon.png"
repo_description: >-
  El repositorio oficial de Creadores Program de F-droid para descargar nuestras apps como CreaTV o LegacySend!

repo_url: "https://creadores-program.github.io/CreaProFDR/repo"

language: "es"

keystore: "CreaProFDR.keystore"
repo_keyalias: "CreaProFDRkey"
