repo_name: "CreaProFDR"
repo_icon: "icon.jpg"
repo_description: "Repositorio oficial de Creadores Program: aplicaciones de IA, herramientas, streaming y juegos optimizados para Android clásico y moderno."

repo_url: "https://creadores-program.github.io/CreaProFDR/repo"

language: "es"

keystore: "CreaProFDR.keystore"
repo_keyalias: "CreaProFDRkey"
repo_web_url: "https://github.com/Creadores-Program/CreaProFDR"
